fix: start:dev fails to start locally
Error: When a manual configuration is not provided, gateway requires an Apollo configuration.

Local development should use NODE_END=local since https://github.com/Pocket/admin-api/pull/361